// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHTwcbDmtDyWmp7lonV2C3i4swM2HFZtg',
    appId: '1:655115030548:web:65417931d351550a141701',
    messagingSenderId: '655115030548',
    projectId: 'dacs3-1695e',
    authDomain: 'dacs3-1695e.firebaseapp.com',
    databaseURL: 'https://dacs3-1695e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacs3-1695e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsHGQqM0aDBSxw1DiIQBptO2e-2tzrtcg',
    appId: '1:655115030548:android:0edac16288e1b93a141701',
    messagingSenderId: '655115030548',
    projectId: 'dacs3-1695e',
    databaseURL: 'https://dacs3-1695e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacs3-1695e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD48RZwbiIrkEclyr103hXj0eZjcuStnLo',
    appId: '1:655115030548:ios:b154843a94d3ef64141701',
    messagingSenderId: '655115030548',
    projectId: 'dacs3-1695e',
    databaseURL: 'https://dacs3-1695e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacs3-1695e.appspot.com',
    iosBundleId: 'com.example.dacs31',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD48RZwbiIrkEclyr103hXj0eZjcuStnLo',
    appId: '1:655115030548:ios:b154843a94d3ef64141701',
    messagingSenderId: '655115030548',
    projectId: 'dacs3-1695e',
    databaseURL: 'https://dacs3-1695e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacs3-1695e.appspot.com',
    iosBundleId: 'com.example.dacs31',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHTwcbDmtDyWmp7lonV2C3i4swM2HFZtg',
    appId: '1:655115030548:web:a4ff69e5c8c7e718141701',
    messagingSenderId: '655115030548',
    projectId: 'dacs3-1695e',
    authDomain: 'dacs3-1695e.firebaseapp.com',
    databaseURL: 'https://dacs3-1695e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacs3-1695e.appspot.com',
  );
}
